# -*- coding: utf-8 -*-
"""
仓库编码规范化执行工具
将扫描识别出的非 UTF-8 文件统一转换为 UTF-8/UTF-8 with BOM，并迁移需要保持原始字节语义的运行期文本到宏头文件。
"""
import argparse
import codecs
import json
import os
from pathlib import Path


BOM = codecs.BOM_UTF8


def is_chinese_char(ch):
    cp = ord(ch)
    return (0x4E00 <= cp <= 0x9FFF) or (0x3400 <= cp <= 0x4DBF) or (0xF900 <= cp <= 0xFAFF)


def parse_args():
    parser = argparse.ArgumentParser(description="Normalize repository encoding.")
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--compiler", default="armcc", choices=["armcc", "armclang"], help="Compiler type")
    parser.add_argument("--files", default="", help="Comma-separated list of files to convert (relative to root)")
    parser.add_argument("--no-bom-files", default="", help="Comma-separated list of files to convert to UTF-8 without BOM")
    parser.add_argument("--macro-header", default="", help="Path to new macro header file (relative to root)")
    parser.add_argument("--macro-name", default="", help="Macro name for migrated Chinese string")
    parser.add_argument("--macro-value", default="", help='Macro value with original-encoding byte escapes, e.g. "PT562\\xB2\\xE2\\n"')
    parser.add_argument("--macro-comment", default="", help="Chinese comment for the macro")
    parser.add_argument("--source-file", default="", help="Source file containing the old Chinese string")
    parser.add_argument("--old-string", default="", help="Old Chinese string literal to replace")
    parser.add_argument("--include-marker", default='#include "includes.h"', help="Marker line to insert new include after")
    parser.add_argument("--audit-json", default="", help="Machine-readable audit JSON generated by scan_encoding.py")
    parser.add_argument("--plan-out", default="", help="Optional JSON path to write dry-run or execution plan")
    parser.add_argument("--dry-run", action="store_true", help="Only generate a plan; do not modify files")
    return parser.parse_args()


def detect_source_encoding(data):
    if data.startswith(BOM):
        return "utf-8-sig"
    for encoding in ("utf-8", "gbk", "big5"):
        try:
            data.decode(encoding)
            return encoding
        except UnicodeDecodeError:
            continue
    scored = []
    for encoding in ("gbk", "big5"):
        try:
            text = data.decode(encoding, errors="replace")
        except Exception:
            continue
        replacement_count = text.count("\ufffd")
        chinese_count = sum(1 for ch in text if is_chinese_char(ch))
        scored.append((encoding, chinese_count, replacement_count))
    if scored:
        scored.sort(key=lambda item: (-item[1], item[2]))
        best_encoding, best_chinese_count, best_replacement_count = scored[0]
        if best_chinese_count >= 8 and best_replacement_count <= max(16, len(data) // 4096):
            return f"{best_encoding}-lossy"
    return "latin-1"


def decode_source_bytes(data, encoding=None):
    resolved_encoding = encoding or detect_source_encoding(data)
    if resolved_encoding.endswith("-lossy"):
        return data.decode(resolved_encoding[:-6], errors="replace"), resolved_encoding
    return data.decode(resolved_encoding), resolved_encoding


def convert_file(filepath, use_bom=True):
    with open(filepath, "rb") as fh:
        data = fh.read()
    text, enc = decode_source_bytes(data)
    text = text.replace("\r\n", "\n").replace("\n", "\r\n")
    with open(filepath, "wb") as fh:
        if use_bom:
            fh.write(BOM)
        fh.write(text.encode("utf-8"))
    print(f"Converted: {filepath} ({enc} -> utf-8{'-sig' if use_bom else ''})")


def create_macro_header(filepath, macro_name, macro_value, macro_comment):
    content = "\r\n".join(
        [
            "#ifndef _TEXT_H",
            "#define _TEXT_H",
            "",
            "/*",
            " * 中文文本集中定义",
            " * 来源：由历史非 UTF-8 编码源码中的运行期文本迁移而来。",
            " * 说明：本文件使用 UTF-8 with BOM 保存；宏值使用原始编码字节转义，保持运行期字节不变。",
            " */",
            "",
            "/* ===== 运行期中文文本 ===== */",
            f'#define {macro_name}  "{macro_value}"  /* {macro_comment} */',
            "",
            "#endif /* _TEXT_H */",
            "",
        ]
    )
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "wb") as fh:
        fh.write(BOM)
        fh.write(content.encode("utf-8"))
    print(f"Created macro header: {filepath}")


def replace_string_in_source(filepath, include_marker, macro_header, old_string, macro_name, source_encoding=None):
    with open(filepath, "rb") as fh:
        data = fh.read()
    if data.startswith(BOM):
        data = data[len(BOM) :]
    text, _ = decode_source_bytes(data, source_encoding)

    inc_line = f'#include "{os.path.basename(macro_header)}"'
    if include_marker in text and inc_line not in text:
        text = text.replace(include_marker, include_marker + "\r\n" + inc_line)

    if old_string in text:
        text = text.replace(old_string, macro_name)
        print(f"Replaced old string in: {filepath}")
    else:
        lines = text.split("\r\n")
        replaced = False
        for idx, line in enumerate(lines):
            if old_string[:10] in line:
                lines[idx] = line.replace(old_string, macro_name)
                replaced = True
                print(f"Replaced line {idx + 1} in: {filepath}")
                break
        if not replaced:
            print(f"WARN: could not find old string in {filepath}")
        text = "\r\n".join(lines)

    text = text.replace("\r\n", "\n").replace("\n", "\r\n")
    with open(filepath, "wb") as fh:
        fh.write(BOM)
        fh.write(text.encode("utf-8"))
    print(f"Fixed source: {filepath}")


def should_use_bom(rel_path, compiler, no_bom_files):
    normalized = rel_path.replace("\\", "/")
    lowered = normalized.lower()
    if normalized in no_bom_files:
        return False
    if lowered.endswith(".mk"):
        return False
    if lowered.endswith((".s", ".asm", ".inc")):
        return False
    if "/startup" in lowered or lowered.startswith("startup"):
        return False
    if any(token in lowered for token in ("startup_", "startup-", "_startup", "crt0", "vectors", "vector_table")):
        return False
    return compiler == "armcc"


def is_plain_text_file(rel_path):
    normalized = rel_path.replace("\\", "/").lower()
    return normalized.endswith((".txt", ".md", ".rst", ".csv", ".json", ".yaml", ".yml", ".ini", ".cfg"))


def resolve_under_root(root, path):
    candidate = Path(path)
    if candidate.is_absolute():
        return candidate
    return Path(root) / candidate


def load_audit_json(root, path):
    return json.loads(resolve_under_root(root, path).read_text(encoding="utf-8"))


def build_plan(audit, compiler, no_bom_files):
    convert_files = []
    migration_candidates = []
    skipped_files = []

    for item in audit.get("results", []):
        file_class = item.get("file_class", "")
        path = item["path"]
        encoding = item.get("encoding", "")
        if encoding in {"utf-8", "utf-8-sig"}:
            skipped_files.append({"path": path, "reason": f"already {encoding}"})
            continue
        if file_class == "comment_only":
            use_bom = should_use_bom(path, compiler, no_bom_files)
            convert_files.append(
                {
                    "path": path,
                    "encoding": encoding,
                    "target_encoding": "utf-8-sig" if use_bom else "utf-8",
                    "use_bom": use_bom,
                }
            )
            continue
        if is_plain_text_file(path):
            use_bom = should_use_bom(path, compiler, no_bom_files)
            convert_files.append(
                {
                    "path": path,
                    "encoding": encoding,
                    "target_encoding": "utf-8-sig" if use_bom else "utf-8",
                    "use_bom": use_bom,
                    "reason": "plain text file can be converted directly",
                }
            )
            continue
        if file_class in {"string_or_runtime", "mixed_comment_and_runtime"}:
            string_lines = [line[0] for line in item.get("lines", []) if any(hit[2] == "string" for hit in line[2])]
            old_string_literals = []
            for line in item.get("lines", []):
                if any(hit[2] == "string" for hit in line[2]):
                    old_string_literals.append(line[1])
            migration_candidates.append(
                {
                    "path": path,
                    "encoding": encoding,
                    "reason": "contains runtime Chinese strings",
                    "string_lines": string_lines,
                    "old_string_literals": old_string_literals,
                }
            )
            continue
        skipped_files.append({"path": path, "reason": f"needs manual review: {file_class}"})

    return {
        "convert_files": convert_files,
        "migration_candidates": migration_candidates,
        "skipped_files": skipped_files,
    }


def write_plan_report(plan, out_path):
    Path(out_path).write_text(json.dumps(plan, ensure_ascii=False, indent=2), encoding="utf-8")


def parse_csv_set(value):
    return {item.strip().replace("\\", "/") for item in value.split(",") if item.strip()}


def apply_plan(root, plan):
    for item in plan["convert_files"]:
        convert_file(os.path.join(root, item["path"]), use_bom=item["use_bom"])


def main():
    args = parse_args()
    root = os.path.abspath(args.root)
    no_bom_files = parse_csv_set(args.no_bom_files)

    if args.audit_json:
        audit = load_audit_json(root, args.audit_json)
        plan = build_plan(audit, compiler=args.compiler, no_bom_files=no_bom_files)
        if args.plan_out:
            write_plan_report(plan, os.path.join(root, args.plan_out))
        else:
            print(json.dumps(plan, ensure_ascii=False, indent=2))
        if args.dry_run:
            print("Dry run complete")
            return
        apply_plan(root, plan)
    else:
        use_bom = args.compiler == "armcc"
        if args.files:
            for rel in args.files.split(","):
                rel = rel.strip()
                if not rel:
                    continue
                convert_file(os.path.join(root, rel), use_bom=should_use_bom(rel, args.compiler, no_bom_files) if rel else use_bom)

        if args.macro_header and args.macro_name and args.macro_value:
            header_path = os.path.join(root, args.macro_header)
            create_macro_header(header_path, args.macro_name, args.macro_value, args.macro_comment or args.macro_name)
            if args.source_file and args.old_string:
                replace_string_in_source(
                    os.path.join(root, args.source_file),
                    args.include_marker,
                    args.macro_header,
                    args.old_string,
                    args.macro_name,
                    source_encoding=None,
                )

    print("Done")


if __name__ == "__main__":
    main()
