# -*- coding: utf-8 -*-
"""
仓库编码规范化执行工具
将扫描识别出的非 UTF-8 文件统一转换为 UTF-8/UTF-8 with BOM。
中文运行期字符串保留在源码中，由 gbk_build.py 在编译时自动处理。
"""
import argparse
import codecs
import json
import os
import re
from pathlib import Path


BOM = codecs.BOM_UTF8

# 中文字符及中文相关符号范围（用于编码检测评分）
_CJK_RANGES = [
    (0x4E00, 0x9FFF),
    (0x3400, 0x4DBF),
    (0xF900, 0xFAFF),
    (0x20000, 0x2A6DF),
    (0xFF00, 0xFFEF),
    (0x3000, 0x303F),
    (0xFE30, 0xFE4F),
    (0x2100, 0x214F),
    (0x00B0, 0x00B0),
    (0x2013, 0x2014),
    (0x2018, 0x2019),
    (0x201C, 0x201D),
    (0x2026, 0x2026),
    (0x00D7, 0x00D7),
    (0x00F7, 0x00F7),
]


def is_chinese_char(ch):
    cp = ord(ch)
    return any(lo <= cp <= hi for lo, hi in _CJK_RANGES)


def parse_args():
    parser = argparse.ArgumentParser(description="Normalize repository encoding to UTF-8.")
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--compiler", default="armcc", choices=["armcc", "armclang"], help="Compiler type")
    parser.add_argument("--files", default="", help="Comma-separated list of files to convert (relative to root)")
    parser.add_argument("--no-bom-files", default="", help="Comma-separated list of files to convert to UTF-8 without BOM")
    parser.add_argument("--audit-json", default="", help="Machine-readable audit JSON generated by scan_encoding.py")
    parser.add_argument("--plan-out", default="", help="Optional JSON path to write dry-run or execution plan")
    parser.add_argument("--dry-run", action="store_true", help="Only generate a plan; do not modify files")
    return parser.parse_args()


def detect_source_encoding(data):
    if data.startswith(BOM):
        return "utf-8-sig"
    try:
        data.decode("utf-8")
        return "utf-8"
    except UnicodeDecodeError:
        pass
    for encoding in ("gbk", "big5"):
        try:
            data.decode(encoding)
            return encoding
        except UnicodeDecodeError:
            continue
    scored = []
    for encoding in ("gbk", "big5"):
        try:
            text = data.decode(encoding, errors="replace")
        except Exception:
            continue
        replacement_count = text.count("\ufffd")
        chinese_count = sum(1 for ch in text if is_chinese_char(ch))
        scored.append((encoding, chinese_count, replacement_count))
    if scored:
        scored.sort(key=lambda item: (-item[1], item[2]))
        best_encoding, best_chinese_count, best_replacement_count = scored[0]
        if best_chinese_count >= 1 and best_replacement_count <= max(32, len(data) // 2048):
            return f"{best_encoding}-lossy"
        if best_replacement_count <= max(16, len(data) // 4096):
            return "gbk-lossy"
    try:
        text = data.decode("gbk", errors="replace")
        if text.count("\ufffd") <= max(32, len(data) // 2048):
            return "gbk-lossy"
    except Exception:
        pass
    return "gbk-lossy"


def decode_source_bytes(data, encoding=None):
    resolved_encoding = encoding or detect_source_encoding(data)
    if resolved_encoding.endswith("-lossy"):
        return data.decode(resolved_encoding[:-6], errors="replace"), resolved_encoding
    return data.decode(resolved_encoding), resolved_encoding


def convert_file(filepath, use_bom=True):
    """将非 UTF-8 文件原地转换为 UTF-8 (with/without BOM)。"""
    with open(filepath, "rb") as fh:
        data = fh.read()
    text, enc = decode_source_bytes(data)
    text = text.replace("\r\n", "\n").replace("\n", "\r\n")
    # 安全网：防止 GBK→UTF-8 转换导致 #include 与下一行合并
    text = re.sub(r'(#include\s+"[^"]+")\s*(\S)', r'\1\r\n\2', text)
    text = re.sub(r'(\")\s*(#endif|#else|#elif)', r'\1\r\n\2', text)
    with open(filepath, "wb") as fh:
        if use_bom:
            fh.write(BOM)
        fh.write(text.encode("utf-8"))
    print(f"  Converted: {filepath} ({enc} -> utf-8{'-sig' if use_bom else ''})")


def should_use_bom(rel_path, compiler, no_bom_files):
    normalized = rel_path.replace("\\", "/")
    lowered = normalized.lower()
    if normalized in no_bom_files:
        return False
    if lowered.endswith(".mk"):
        return False
    if lowered.endswith((".s", ".asm", ".inc")):
        return False
    if "/startup" in lowered or lowered.startswith("startup"):
        return False
    if any(token in lowered for token in ("startup_", "startup-", "_startup", "crt0", "vectors", "vector_table")):
        return False
    return compiler == "armcc"


def is_plain_text_file(rel_path):
    normalized = rel_path.replace("\\", "/").lower()
    return normalized.endswith((".txt", ".md", ".rst", ".csv", ".json", ".yaml", ".yml", ".ini", ".cfg"))


def resolve_under_root(root, path):
    candidate = Path(path)
    if candidate.is_absolute():
        return candidate
    return Path(root) / candidate


def load_audit_json(root, path):
    return json.loads(resolve_under_root(root, path).read_text(encoding="utf-8"))


def build_plan(audit, compiler, no_bom_files):
    """根据审计结果生成转换计划。

    所有非 UTF-8 文件统一转换为 UTF-8（with/without BOM）。
    含运行期中文的文件也一并转换，后续由 gbk_build.py 处理编译时 GBK 转换。
    """
    convert_files = []
    skipped_files = []

    for item in audit.get("results", []):
        path = item["path"]
        encoding = item.get("encoding", "")
        file_class = item.get("file_class", "")

        if encoding in {"utf-8", "utf-8-sig"}:
            skipped_files.append({"path": path, "reason": f"already {encoding}"})
            continue

        use_bom = should_use_bom(path, compiler, no_bom_files)
        target = "utf-8-sig" if use_bom else "utf-8"

        # comment_only / string_or_runtime / mixed → 统一转换
        # gbk_build.py 会在编译时处理运行期中文
        if file_class in {"comment_only", "string_or_runtime", "mixed_comment_and_runtime"}:
            convert_files.append({
                "path": path, "encoding": encoding,
                "target_encoding": target, "use_bom": use_bom,
            })
            continue

        if is_plain_text_file(path):
            convert_files.append({
                "path": path, "encoding": encoding,
                "target_encoding": target, "use_bom": use_bom,
                "reason": "plain text file",
            })
            continue

        if file_class == "code_only_needs_review":
            lowered = path.lower()
            if lowered.endswith((".mk", ".s", ".asm", ".inc", ".txt", ".md", ".bat", ".cmd")) or \
               "startup" in lowered:
                convert_files.append({
                    "path": path, "encoding": encoding,
                    "target_encoding": target, "use_bom": use_bom,
                    "reason": f"auto-convert {file_class}",
                })
                continue

        skipped_files.append({"path": path, "reason": f"needs manual review: {file_class}"})

    return {
        "convert_files": convert_files,
        "skipped_files": skipped_files,
    }


def write_plan_report(plan, out_path):
    Path(out_path).write_text(json.dumps(plan, ensure_ascii=False, indent=2), encoding="utf-8")


def parse_csv_set(value):
    return {item.strip().replace("\\", "/") for item in value.split(",") if item.strip()}


def apply_plan(root, plan):
    """执行编码转换计划。"""
    if plan["convert_files"]:
        print(f"\n=== Converting {len(plan['convert_files'])} file(s) ===")
        for item in plan["convert_files"]:
            convert_file(os.path.join(root, item["path"]), use_bom=item["use_bom"])

    if plan.get("skipped_files"):
        print(f"\n=== Skipped {len(plan['skipped_files'])} file(s) ===")
        for item in plan["skipped_files"]:
            print(f"  {item['path']}: {item['reason']}")

    print(f"\n=== Summary ===")
    print(f"  Converted: {len(plan['convert_files'])} file(s)")
    print(f"  Skipped: {len(plan.get('skipped_files', []))} file(s)")


def main():
    args = parse_args()
    root = os.path.abspath(args.root)
    no_bom_files = parse_csv_set(args.no_bom_files)

    if args.audit_json:
        audit = load_audit_json(root, args.audit_json)
        plan = build_plan(audit, compiler=args.compiler, no_bom_files=no_bom_files)
        if args.plan_out:
            write_plan_report(plan, os.path.join(root, args.plan_out))
        else:
            print(json.dumps(plan, ensure_ascii=False, indent=2))
        if args.dry_run:
            print("Dry run complete")
            return
        apply_plan(root, plan)
    else:
        use_bom = args.compiler == "armcc"
        if args.files:
            for rel in args.files.split(","):
                rel = rel.strip()
                if not rel:
                    continue
                convert_file(os.path.join(root, rel),
                           use_bom=should_use_bom(rel, args.compiler, no_bom_files) if rel else use_bom)

    print("Done")


if __name__ == "__main__":
    main()
